apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]                    # override docker entrypoint
    args: ["HOSTNAME", "KUBERNETES_PORT"]    # override docker command
  restartPolicy: OnFailure
