apiVersion: v1
kind: Pod
metadata:
  name: cm-test
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: [ "/bin/sh", "-c", "ls /etc/config/; sleep 50" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: astra-config
  restartPolicy: Never
