apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mongoinit
  name: mongoinit
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: mongoinit
    spec:
      containers:
      - command: ["/bin/bash","-c"]
        args: ["cp /mongo-init/mongo-init.sh ./script.sh;chmod +x script.sh; ./script.sh"]
        image: amazonlinux
        imagePullPolicy: IfNotPresent
        name: mongoinit
        volumeMounts:
          - name: mongo-init-volume
            mountPath: /mongo-init        
      restartPolicy: Never
      # Mounting path on my windows matchine and using docker-desktop kubernetes
      volumes:
        - name: mongo-init-volume
          hostPath:
            path: /run/desktop/mnt/host/c/users/public/Documents
            type: Directory